### ISSUE TITLE
Upstream breakage in latest astropy

### ISSUE THREAD

**Issue by bennahugo** [ska-sa/tigger-lsm#19]
```
[0m[91m2020-11-03 18:16:59	INFO	imager::createFTMachine() 	Performing interferometric gridding...
[0m[91m2020-11-03 18:17:01	INFO	ImageFitsConverter::ImageToFITS 	Copying '/src/pyxis/Pyxis/recipies/meqtrees-batch-test/WSRT.MS.MODEL_DATA.channel.1ch.img' to file Copying plane by plane (1048576 pixels).
[0mlwimager normally ended
Image /src/pyxis/Pyxis/recipies/meqtrees-batch-test/WSRT.MS.MODEL_DATA.channel.1ch.fits ready. No image viewer selected (see TDL Exec menu).
[91mTraceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/Timba/TDL/Compile.py", line 139, in import_tdl_module
    _tdlmod = imp.load_source(modname,filename,infile);
  File "/usr/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/src/pyxis/Pyxis/recipies/meqtrees-batch-test/sim.py", line 70, in <module>
    meqmaker.add_sky_models([gridded_sky,transient_sky,fitsimage_sky,lsm,TiggerSkyModel(verbose=2)]);
  File "/usr/local/lib/python3.6/dist-packages/Cattery/Siamese/OMS/tigger_lsm.py", line 45, in TiggerSkyModel
    classobj = importTigger(verbose=verbose);
  File "/usr/local/lib/python3.6/dist-packages/Cattery/Siamese/OMS/tigger_lsm.py", line 18, in importTigger
    import Tigger.SiameseInterface
  File "/usr/local/lib/python3.6/dist-packages/Tigger/SiameseInterface.py", line 46, in <module>
    from Tigger.Models.SkyModel import SkyModel
  File "/usr/local/lib/python3.6/dist-packages/Tigger/Models/SkyModel.py", line 31, in <module>
    from Tigger.Coordinates import angular_dist_pos_angle, DEG
  File "/usr/local/lib/python3.6/dist-packages/Tigger/Coordinates.py", line 62, in <module>
    from astLib.astWCS import WCS
  File "/usr/local/lib/python3.6/dist-packages/astLib/astWCS.py", line 29, in <module>
    import astropy.wcs as apywcs
  File "/usr/local/lib/python3.6/dist-packages/astropy/wcs/__init__.py", line 26, in <module>
    from .wcs import *
  File "/usr/local/lib/python3.6/dist-packages/astropy/wcs/wcs.py", line 57, in <module>
    from .wcsapi.fitswcs import FITSWCSAPIMixin, SlicedFITSWCS
  File "/usr/local/lib/python3.6/dist-packages/astropy/wcs/wcsapi/fitswcs.py", line 11, in <module>
    from astropy.coordinates import SpectralCoord, Galactic, ICRS
  File "/usr/local/lib/python3.6/dist-packages/astropy/coordinates/__init__.py", line 16, in <module>
    from .builtin_frames import *
  File "/usr/local/lib/python3.6/dist-packages/astropy/coordinates/builtin_frames/__init__.py", line 46, in <module>
    from . import supergalactic_transforms
  File "/usr/local/lib/python3.6/dist-packages/astropy/coordinates/builtin_frames/supergalactic_transforms.py", line 14, in <module>
    @frame_transform_graph.transform(StaticMatrixTransform, Galactic, Supergalactic)
  File "/usr/local/lib/python3.6/dist-packages/astropy/coordinates/transformations.py", line 674, in deco
    register_graph=self, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/astropy/coordinates/transformations.py", line 1251, in __init__
    matrix = matrix()
  File "/usr/local/lib/python3.6/dist-packages/astropy/coordinates/builtin_frames/supergalactic_transforms.py", line 17, in gal_to_supergal
    mat2 = rotation_matrix(90 - Supergalactic._nsgp_gal.b.degree, 'y')
  File "/usr/local/lib/python3.6/dist-packages/astropy/coordinates/baseframe.py", line 1638, in __getattr__
    in_frame_units=True)
  File "/usr/local/lib/python3.6/dist-packages/astropy/coordinates/baseframe.py", line 1110, in represent_as
    datakwargs[comp] = datakwargs[comp].to(new_attr_unit)
  File "/usr/local/lib/python3.6/dist-packages/astropy/units/quantity.py", line 689, in to
    return self._new_view(self._to_value(unit, equivalencies), unit)
  File "/usr/local/lib/python3.6/dist-packages/astropy/units/quantity.py", line 661, in _to_value
    equivalencies=equivalencies)
  File "/usr/local/lib/python3.6/dist-packages/astropy/units/core.py", line 987, in to
    return self._get_converter(other, equivalencies=equivalencies)(value)
  File "/usr/local/lib/python3.6/dist-packages/astropy/units/core.py", line 918, in _get_converter
    raise exc
  File "/usr/local/lib/python3.6/dist-packages/astropy/units/core.py", line 904, in _get_converter
    self, other, self._normalize_equivalencies(equivalencies))
  File "/usr/local/lib/python3.6/dist-packages/astropy/units/core.py", line 888, in _apply_equivalencies
    unit_str, other_str))
astropy.units.core.UnitConversionError: 'deg' (angle) and 'deg' (angle) are not convertible
E
======================================================================
ERROR: batch_test.testMeqtreesBatchJob
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/src/pyxis/Pyxis/recipies/meqtrees-batch-test/batch_test.py", line 170, in testMeqtreesBatchJob
    mod,ns,msg = Compile.compile_file(mqs,script,config=None);
  File "/usr/local/lib/python3.6/dist-packages/Timba/TDL/Compile.py", line 305, in compile_file
    (tdlmod,text) = import_tdl_module(filename,text=text,config=config);
  File "/usr/local/lib/python3.6/dist-packages/Timba/TDL/Compile.py", line 167, in import_tdl_module
    raise TDL.CumulativeError(*ns.GetErrors());
Timba.TDL.TDLimpl.CumulativeError: 
 [  1] 'deg' (angle) and 'deg' (angle) are not convertible
```

**Comment by bennahugo** [comment]
Trying to track this down, but it seems the failure mode does not reproduce right now upon import of 
```
from Tigger.Coordinates import angular_dist_pos_angle, DEG
```
with a fresh installation of python-tigger-lsm

rerunning the test right now to see if the upstream breakage has been fixed in the mean time

**Comment by bennahugo** [comment]
Seems it is still there, but it is not clear under what import conditions this is being triggered. Will need to dig deeper and raise this to astropy

**Comment by bmerry** [comment]
I seem to recall that Meqtrees does some funky things with importing. Is it possible that it's somehow imported astropy twice, and thus ended up with two degrees units? Astropy has a short-cut for identity unit conversions which tests `if self is other`.

**Comment by bennahugo** [comment]
O.o that may be it. I'll have a check later this week

**Comment by bennahugo** [comment]
Fixed downstream in Timba
